version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    # Instead of volume mount, try without it first to see if that's the issue
    # volumes:
    #  - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SECRET_KEY=secret_key_nurai
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nurai_dev
      - DB_PORT=5432
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nurai_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data: